import Navigation from "../components/navigagion"
import '../css/global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log('??')
  return (
    <html lang="en">
      <body>
        {<Navigation/>}
        {children}</body>
    </html>
  )
}
